config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Sidekiq::Web => '/sidekiq'
  mount Resque::Server, :at => "/resque"
  resources :histories

  post 'functions/show_device'

  post 'functions/update_device'

  post 'functions/show_history'

  post 'functions/show_tracking'

  post 'functions/send_command'

  post 'functions/update_device_config'

  post  'functions/get_storyInfo'

  post 'functions/get_userInfo'

  post 'functions/activate_device'

  post 'functions/bind_device'

  post 'functions/send_voice_file'

  post 'functions/voice_file_list'

  post 'functions/play_voice_file'

  post 'functions/baby_health_info'

  post 'functions/flower_reward'

  resources :user_devices

  namespace :admin do
    resources :manage_users
  end

  namespace :admin do
    resources :logins, only: [:new, :create, :destroy]
    get 'logins/activate_socket'
    root 'logins#new'
  end

  post 'devices/reset' => 'devices#reset', as: :reset_device

  get 'devices/reset_page' => 'devices#reset_page', as: :reset_page
  
  resources :devices

  resources :users

  get 'auths/send_captcha'

  post 'auths/check_captcha'

  post 'auths/register'

  post 'auths/check_device'

  post 'auths/login'

  post 'auths/reset_password'

  post 'auths/is_registered'

end

app/models/admin/manage_user.rb
# == Schema Information
#
# Table name: admin_manage_users
#
#  id         :integer          not null, primary key
#  user_name  :string(255)
#  password   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  role       :integer
#

require 'digest/sha1'

class Admin::ManageUser < ActiveRecord::Base
  before_save :encrypt_password

  def encrypt_password
    if self.password.present?
      self.password = Digest::SHA1.hexdigest(self.password)
    else
      self.password = self.password_was
    end
  end

  def registered?
    u = Admin::ManageUser.find_by(user_name: self.user_name, password: Digest::SHA1.hexdigest(self.password))
    if u != nil
      self.id = u.id
      true
    else
      false
    end
  end
end

app/controllers/admin/manage_users_controller.rb
class Admin::ManageUsersController < ApplicationController
  before_action :set_admin_manage_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  # GET /admin/manage_users
  # GET /admin/manage_users.json
  def index
    @admin_manage_users = Admin::ManageUser.all
  end

  # GET /admin/manage_users/1
  # GET /admin/manage_users/1.json
  def show
  end

  # GET /admin/manage_users/new
  def new
    @admin_manage_user = Admin::ManageUser.new
  end

  # GET /admin/manage_users/1/edit
  def edit
  end

  # POST /admin/manage_users
  # POST /admin/manage_users.json
  def create
    @admin_manage_user = Admin::ManageUser.new(admin_manage_user_params)

    respond_to do |format|
      if @admin_manage_user.save
        format.html { redirect_to @admin_manage_user, notice: 'Manage user was successfully created.' }
        format.json { render :show, status: :created, location: @admin_manage_user }
      else
        format.html { render :new }
        format.json { render json: @admin_manage_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/manage_users/1
  # PATCH/PUT /admin/manage_users/1.json
  def update
    respond_to do |format|
      if @admin_manage_user.update(admin_manage_user_params)
        format.html { redirect_to @admin_manage_user, notice: 'Manage user was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_manage_user }
      else
        format.html { render :edit }
        format.json { render json: @admin_manage_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/manage_users/1
  # DELETE /admin/manage_users/1.json
  def destroy
    @admin_manage_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_manage_users_url, notice: 'Manage user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_manage_user
      @admin_manage_user = Admin::ManageUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_manage_user_params
      params.require(:admin_manage_user).permit(:user_name, :password)
    end
end

app/helpers/admin/manage_users_helper.rb
module Admin::ManageUsersHelper
end

app/views/admin/manage_users/_form.html.erb
   <%= form_for(@admin_manage_user) do |f| %>
  <% if @admin_manage_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_manage_user.errors.count, "error") %> prohibited this admin_manage_user from being saved:</h2>

      <ul>
      <% @admin_manage_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/manage_users/edit.html.erb
<h1>Editing Admin Manage User</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_manage_user %> |
<%= link_to 'Back', admin_manage_users_path %>

app/views/admin/manage_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Manage Users</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_manage_users.each do |admin_manage_user| %>
      <tr>
        <td><%= admin_manage_user.user_name %></td>
        <td><%= admin_manage_user.password %></td>
        <td><%= link_to 'Show', admin_manage_user %></td>
        <td><%= link_to 'Edit', edit_admin_manage_user_path(admin_manage_user) %></td>
        <td><%= link_to 'Destroy', admin_manage_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manage user', new_admin_manage_user_path %>

app/views/admin/manage_users/new.html.erb
<h1>New Admin Manage User</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_manage_users_path %>

app/views/admin/manage_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @admin_manage_user.user_name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin_manage_user.password %>
</p>

<%= link_to 'Edit', edit_admin_manage_user_path(@admin_manage_user) %> |
<%= link_to 'Back', admin_manage_users_path %>