config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Sidekiq::Web => '/sidekiq'
  mount Resque::Server, :at => "/resque"
  resources :histories

  post 'functions/show_device'

  post 'functions/update_device'

  post 'functions/show_history'

  post 'functions/show_tracking'

  post 'functions/send_command'

  post 'functions/update_device_config'

  post  'functions/get_storyInfo'

  post 'functions/get_userInfo'

  post 'functions/activate_device'

  post 'functions/bind_device'

  post 'functions/send_voice_file'

  post 'functions/voice_file_list'

  post 'functions/play_voice_file'

  post 'functions/baby_health_info'

  post 'functions/flower_reward'

  resources :user_devices

  namespace :admin do
    resources :manage_users
  end

  namespace :admin do
    resources :logins, only: [:new, :create, :destroy]
    get 'logins/activate_socket'
    root 'logins#new'
  end

  post 'devices/reset' => 'devices#reset', as: :reset_device

  get 'devices/reset_page' => 'devices#reset_page', as: :reset_page
  
  resources :devices

  resources :users

  get 'auths/send_captcha'

  post 'auths/check_captcha'

  post 'auths/register'

  post 'auths/check_device'

  post 'auths/login'

  post 'auths/reset_password'

  post 'auths/is_registered'

end

app/models/user_device.rb
# == Schema Information
#
# Table name: user_devices
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  device_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_user_devices_on_device_id  (device_id)
#  index_user_devices_on_user_id    (user_id)
#

class UserDevice < ActiveRecord::Base
  belongs_to :user
  belongs_to :device
  validates :user_id, presence: true
  #validates :device_id, presence: true

  def mobile
    u = self.user
    u.mobile if u
  end

  def deviceId
    d = self.device
    d.series_code if d
  end
end

app/controllers/user_devices_controller.rb
class UserDevicesController < ApplicationController
  before_action :set_user_device, only: [:show, :edit, :update, :destroy]

  # GET /user_devices
  # GET /user_devices.json
  def index
    @user_devices = UserDevice.all.page(params[:page])
  end

  # GET /user_devices/1
  # GET /user_devices/1.json
  def show
  end

  # GET /user_devices/new
  def new
    @user_device = UserDevice.new
  end

  # GET /user_devices/1/edit
  def edit
  end

  # POST /user_devices
  # POST /user_devices.json
  def create
    if user_device_params[:mobile] && user_device_params[:deviceId]
      user = User.find_by(mobile: user_device_params[:mobile])
      device = Device.find_device(user_device_params[:deviceId])
      @user_device = UserDevice.new(user: user, device: device)
    else
      @user_device = UserDevice.new(user_device_params)
    end
    respond_to do |format|
      if @user_device.save
        format.html { redirect_to @user_device, notice: 'User device was successfully created.' }
        format.json { render :show, status: :created, location: @user_device }
      else
        format.html { render :new }
        format.json { render json: @user_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_devices/1
  # PATCH/PUT /user_devices/1.json
  def update
    respond_to do |format|
      if @user_device.update(user_device_params)
        format.html { redirect_to @user_device, notice: 'User device was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_device }
      else
        format.html { render :edit }
        format.json { render json: @user_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_devices/1
  # DELETE /user_devices/1.json
  def destroy
    @user_device.destroy
    respond_to do |format|
      format.html { redirect_to user_devices_url, notice: 'User device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_device
      @user_device = UserDevice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_device_params
      params.require(:user_device).permit(:user_id, :device_id, :mobile, :deviceId)
    end
end

app/helpers/user_devices_helper.rb
module UserDevicesHelper
end

app/views/user_devices/_form.html.erb
<%= form_for(@user_device) do |f| %>
  <% if @user_device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_device.errors.count, "error") %> prohibited this user_device from being saved:</h2>

      <ul>
      <% @user_device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "user(mobile)" %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label "device(deviceId)" %><br>
    <%= f.text_field :deviceId %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_devices/edit.html.erb
<h1>Editing User Device</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_device %> |
<%= link_to 'Back', user_devices_path %>

app/views/user_devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Devices</h1>
<%= link_to 'New User device', new_user_device_path %>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Device</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_devices.each do |user_device| %>
      <tr>
        <td><%= user_device.user.mobile %></td>
        <td>
          <% if(user_device.device != nil) %>
          <%= user_device.device.series_code %>
          <% else %>
          <%= "nil" %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_device %></td>
        <td><%= link_to 'Edit', edit_user_device_path(user_device) %></td>
        <td><%= link_to 'Destroy', user_device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @user_devices %>

<br>

app/views/user_devices/new.html.erb
<h1>New User Device</h1>

<%= render 'form' %>

<%= link_to 'Back', user_devices_path %>

app/views/user_devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_device.user %>
</p>

<p>
  <strong>Device:</strong>
  <%= @user_device.device %>
</p>

<%= link_to 'Edit', edit_user_device_path(@user_device) %> |
<%= link_to 'Back', user_devices_path %>