config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Sidekiq::Web => '/sidekiq'
  mount Resque::Server, :at => "/resque"
  resources :histories

  post 'functions/show_device'

  post 'functions/update_device'

  post 'functions/show_history'

  post 'functions/show_tracking'

  post 'functions/send_command'

  post 'functions/update_device_config'

  post  'functions/get_storyInfo'

  post 'functions/get_userInfo'

  post 'functions/activate_device'

  post 'functions/bind_device'

  post 'functions/send_voice_file'

  post 'functions/voice_file_list'

  post 'functions/play_voice_file'

  post 'functions/baby_health_info'

  post 'functions/flower_reward'

  resources :user_devices

  namespace :admin do
    resources :manage_users
  end

  namespace :admin do
    resources :logins, only: [:new, :create, :destroy]
    get 'logins/activate_socket'
    root 'logins#new'
  end

  post 'devices/reset' => 'devices#reset', as: :reset_device

  get 'devices/reset_page' => 'devices#reset_page', as: :reset_page
  
  resources :devices

  resources :users

  get 'auths/send_captcha'

  post 'auths/check_captcha'

  post 'auths/register'

  post 'auths/check_device'

  post 'auths/login'

  post 'auths/reset_password'

  post 'auths/is_registered'

end

app/models/history.rb
# == Schema Information
#
# Table name: histories
#
#  id                 :integer          not null, primary key
#  data_type          :integer
#  data_content       :text(65535)
#  location_code      :string(255)
#  location_type      :string(255)
#  data_stamp_address :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  device_id          :integer
#  lng                :decimal(9, 6)
#  lat                :decimal(9, 6)
#  data_description   :string(255)
#
# Indexes
#
#  index_histories_on_device_id  (device_id)
#

class History < ActiveRecord::Base
  belongs_to :device
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all.page(params[:page])
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:user_id, :data_type, :data_content, :location_code, :location_type, :data_stamp_address, :lng, :lat)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_for(@history) do |f| %>
  <% if @history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% @history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :device_id %><br>
    <%= f.text_field :device_id %>
  </div>
  <div class="field">
    <%= f.label :data_type %><br>
    <%= f.number_field :data_type %>
  </div>
  <div class="field">
    <%= f.label :data_content %><br>
    <%= f.text_field :data_content %>
  </div>
  <div class="field">
    <%= f.label :location_code %><br>
    <%= f.text_field :location_code %>
  </div>
  <div class="field">
    <%= f.label :location_type %><br>
    <%= f.text_field :location_type %>
  </div>
  <div class="field">
    <%= f.label :data_stamp_address %><br>
    <%= f.text_field :data_stamp_address %>
  </div>
    <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing History</h1>

<%= render 'form' %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Histories</h1>
<%= link_to 'New History', new_history_path %>
<table>
  <thead>
    <tr>
      <th>Device</th>
      <th>Data type</th>
      <th>Data content</th>
      <th>Location code</th>
      <th>Location type</th>
      <th>Data stamp address</th>
      <th>Time Stamp</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td>
          <% if history.device %>
            <%= history.device.series_code %>
          <% else %>
            <%= nil %>
          <% end %>
        </td>
        <td><%= history.data_type %></td>
        <td><%= history.data_content %></td>
        <td><%= history.location_code %></td>
        <td><%= history.location_type %></td>
        <td><%= history.data_stamp_address %></td>
        <td><%= history.created_at.to_s %></td>
        <td><%= history.lng %></td>
        <td><%= history.lat %></td>
        <td><%= link_to 'Show', history %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @histories %>

<br>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form' %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User device:</strong>
  <% if @history.device %>
    <%= @history.device.series_code %>
  <% else %>
    <%= nil %>
  <% end %>
</p>

<p>
  <strong>Data type:</strong>
  <%= @history.data_type %>
</p>

<p>
  <strong>Data content:</strong>
  <%= @history.data_content %>
</p>

<p>
  <strong>Location code:</strong>
  <%= @history.location_code %>
</p>

<p>
  <strong>Location type:</strong>
  <%= @history.location_type %>
</p>

<p>
  <strong>Data stamp address:</strong>
  <%= @history.data_stamp_address %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @history.lng %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @history.lat %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>