config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Sidekiq::Web => '/sidekiq'
  mount Resque::Server, :at => "/resque"
  resources :histories

  post 'functions/show_device'

  post 'functions/update_device'

  post 'functions/show_history'

  post 'functions/show_tracking'

  post 'functions/send_command'

  post 'functions/update_device_config'

  post  'functions/get_storyInfo'

  post 'functions/get_userInfo'

  post 'functions/activate_device'

  post 'functions/bind_device'

  post 'functions/send_voice_file'

  post 'functions/voice_file_list'

  post 'functions/play_voice_file'

  post 'functions/baby_health_info'

  post 'functions/flower_reward'

  resources :user_devices

  namespace :admin do
    resources :manage_users
  end

  namespace :admin do
    resources :logins, only: [:new, :create, :destroy]
    get 'logins/activate_socket'
    root 'logins#new'
  end

  post 'devices/reset' => 'devices#reset', as: :reset_device

  get 'devices/reset_page' => 'devices#reset_page', as: :reset_page
  
  resources :devices

  resources :users

  get 'auths/send_captcha'

  post 'auths/check_captcha'

  post 'auths/register'

  post 'auths/check_device'

  post 'auths/login'

  post 'auths/reset_password'

  post 'auths/is_registered'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YongWa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://cdn.socket.io/socket.io-1.3.4.js"></script>
  <style type="text/css">
  html,body{
    height: 100%
}
  </style>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">YongWa</a>
        </div>
        <nav>
          <ul class="nav navbar-nav pull-right">
            <% if session[:login] != nil %>
              <li><%= link_to "users", users_path %></li>
              <li><%= link_to "user_devices", user_devices_path %></li>
              <li><%= link_to "histories", histories_path %></li>
              <li><%= link_to "devices", devices_path %></li>
              <li><%= link_to "socket listen", "#", id: "socket" %></li>
            <% end %>

            <% if session[:login] || session[:login_role_1] %>
              <!--<li><%= link_to 'Monitoring', sidekiq_web_path %></li> -->
              <li><%= link_to "logout", admin_login_path(id: 1), method: :delete %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  <div class="container">
    <%= yield %>
<!--     <div class="navbar navbar-fixed-bottom">
      <blockquote class="blockquote-reverse">
        <footer>Yong Wa Admin by<cite title="海之槛歌">海之槛歌</cite></footer>
      </blockquote>
    </div> -->
  </div>
</body>

<%= javascript_tag do %>
  
$( document ).ready(function() {
  $( "table" ).addClass( "table table-hover table-bordered" );

  $( "form" ).css({
    marginTop: "30px"
  });
  $( "form" ).addClass( "form-horizontal" );
  $( "form div" ).addClass( "form-group" );
  $( "form label" ).addClass( "col-sm-3 control-label" );
  $( "form input:visible" ).not( "input[name='commit']" ).addClass( "form-control" );  
  $( "form input:visible" ).not( "input[name='commit']" ).wrap( "<div class='col-sm-4'></div>" );
  $( "br" ).remove();

  $( "input[name='commit']" ).addClass( "btn btn-primary" ); 
  $( "input[name='commit']" ).wrap( "<div class='col-sm-offset-3 col-sm-4'></div>" );
  
  var socket_open = <%= ResqueSocket.is_port_open? %>;
  if( !socket_open ) {
    $("a[id='socket']").css({
      color: '#00dd00'
    });
  }

  $("a[id='socket']").click(function( event ) {
    event.preventDefault();
    $.ajax({
      url: "/admin/logins/activate_socket",
      type: "get",
      success: function (data, status, xhr) {
        if(data.active) {
          $("a[id='socket']").css({
            color: '#00dd00'
          });
        }
      }
    });
  });

});  

 
<!--   var socket = io('localhost:5001');
  socket.on('user-created', function(user){
    alert('Welcome');
    console.log('Welcome')
  });
 -->


<% end %>

</html>